In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression

In [2]:
x = np.array([[1,2,3,0],[4,5,6,1],[7,8,9,1],[4,3,2,0],[1,2,3,0],[4,5,6,1],[7,8,9,1],[4,3,2,0],[1,2,3,0],[4,5,6,1],[7,8,9,1],[4,3,2,0],[1,2,3,0],[4,5,6,1],[7,8,9,1],[4,3,2,0]])
x = sorted(x,key = lambda a:a[3])
for i in x:
    print(i)

[1 2 3 0]
[4 3 2 0]
[1 2 3 0]
[4 3 2 0]
[1 2 3 0]
[4 3 2 0]
[1 2 3 0]
[4 3 2 0]
[4 5 6 1]
[7 8 9 1]
[4 5 6 1]
[7 8 9 1]
[4 5 6 1]
[7 8 9 1]
[4 5 6 1]
[7 8 9 1]


In [3]:
x = np.array(x)
i = x[:,3]
print(i.shape)

(16,)


# Importing Data

In [4]:
data = pd.read_csv(r"G:\Coding Blocks\Documents\fashion.csv")
data.head(n=5)

label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0      0       0       0       0       0       0       0       0       9   
1      1       0       0       0       0       0       0       0       0   
2      2       0       0       0       0       0       0      14      53   
3      2       0       0       0       0       0       0       0       0   
4      3       0       0       0       0       0       0       0       0   

   pixel9    ...     pixel775  pixel776  pixel777  pixel778  pixel779  \
0       8    ...          103        87        56         0         0   
1       0    ...           34         0         0         0         0   
2      99    ...            0         0         0         0        63   
3       0    ...          137       126       140         0       133   
4       0    ...            0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  pixel784  
0         0         0         0         0         0  
1         0         0         0         0         0  
2        53        31         0         0         0  
3       224       222        56         0         0  
4         0         0         0         0         0  

[5 rows x 785 columns]

In [5]:
train = data.values
print(type(train))
print(train.shape)
print(train[:5,])

<class 'numpy.ndarray'>
(10000, 785)
[[ 0  0  0 ...  0  0  0]
 [ 1  0  0 ...  0  0  0]
 [ 2  0  0 ...  0  0  0]
 [ 2  0  0 ... 56  0  0]
 [ 3  0  0 ...  0  0  0]]


In [6]:
train = sorted(train,key = lambda x:x[0])
train = np.array(train)
print(train.shape)
print(train[:5,])

(10000, 785)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]]


In [7]:
i = train[:,0]
print(i.shape)
print(i[-1])
i.reshape(10000,1)
print(i)

(10000,)
9
[0 0 0 ... 9 9 9]


In [8]:
def idex(i,num):
    return list(i).index(num)

In [9]:
z = idex(i,1)
print(z)

1000


In [10]:
classes = list()
labels = list()
print(i[-1])

9


# Deviding the train dataset according to labels and storing in list

In [11]:
def construct():
    t = int()
    prev = 0
    for z in range(1,10):
        t = idex(i,z)
        temp = train[prev:t,1:]
        temp2 = train[prev:t,0]
        labels.append(temp2)
        print(temp.shape)
        classes.append(temp)
        prev = t
    temp = train[t:,1:]
    temp2= train[t:,0]
    labels.append(temp)
    classes.append(temp)

construct()
print(classes[8].shape)

(1000, 784)
(1000, 784)
(1000, 784)
(1000, 784)
(1000, 784)
(1000, 784)
(1000, 784)
(1000, 784)
(1000, 784)
(1000, 784)


In [12]:
print(classes[4])


[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ... 18  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]


In [13]:
t1 = np.array([[1],[2],[3]])
print(t1.shape)
h = np.append([[0],[1]],[[1, 2, 3], [4, 5, 6]], axis=1)
print(h)

(3, 1)
[[0 1 2 3]
 [1 4 5 6]]


# Assignment Starts Here
- Note 1: The self made logistic regression algo is giving run-time error with reasons like : exponent value overflow

In [16]:
# Algorithm
def hypothesis(x,theta,bias):
    result = bias + np.dot(x,theta)
    return sigmoid(result)

def sigmoid(a):
    return 1.0/(1.0 + np.exp(-1.0*a))   # Use floats for accurate results

def error(x,theta,y,bias):
    it = x.shape[0]
    e = 0.0
    for i in range(it):
        h = hypothesis(x[i],theta,bias)
        e += y[i]*np.log2(h) + (1-y[i])*np.log2(1-h)
    return -e/it

def grad(x,y,theta,bias,batch_size = 1):
    it = x.shape[0]
    indices = np.arange(it)
    np.random.shuffle(indices)
    indices = indices[:batch_size]
    g =  np.zeros(theta.shape)
    g_b = 0.0
    for i in indices:
        h = hypothesis(x[i],theta,bias)
        g += (y[i] - h)*x[i]
        g_b += (y[i] - h)
    g /= it
    g_b /= it
    return (g,g_b)

def grad_des(x,y,theta,bias,learning_rate = 0.1):
    e =  error(x,theta,y,bias)
    g,g_b = grad(x,y,theta,bias)
    theta = theta + learning_rate*g
    bias = bias + learning_rate*g_b
    return theta,bias

def predict(x,theta,bias):
    
    confidence = hypothesis(x,theta,bias)
    if confidence<0.5:
        return 0
    else:
        return 1
    

In [96]:
# print(labels[1])
print(labels[1].shape)

(1000,)


In [21]:
theta1 = np.random.random((classes[0].shape[1],))
print(theta1)
bias1 = np.random.random()

[0.10055399 0.65979212 0.56288563 0.03868751 0.40500411 0.52774836
 0.90952623 0.60902317 0.44042246 0.35228647 0.23809964 0.83175538
 0.76079792 0.65249102 0.77859318 0.82554385 0.08760599 0.44782671
 0.24870423 0.11171974 0.05644657 0.91511332 0.25932164 0.60482642
 0.95980117 0.40337086 0.28001152 0.59582329 0.37892098 0.01045775
 0.3179218  0.91031908 0.84615876 0.43627448 0.50908655 0.06924123
 0.4020001  0.20557833 0.92490045 0.47501873 0.85402762 0.97318038
 0.8044622  0.50431006 0.88048611 0.592924   0.89664275 0.53199249
 0.43074751 0.99068162 0.47061067 0.71709493 0.38684101 0.12337848
 0.69153924 0.01241124 0.93106193 0.9347429  0.99713499 0.78229242
 0.96622409 0.92165525 0.95638822 0.65682596 0.09669044 0.82563354
 0.58058752 0.40651867 0.90564113 0.07752342 0.36606484 0.08563744
 0.86271982 0.68633129 0.13896292 0.31041668 0.94029853 0.26876979
 0.8311865  0.31141499 0.40819874 0.83740935 0.153213   0.30248779
 0.79524362 0.56695285 0.45105948 0.17751885 0.45176863 0.4813

# for labels 0 and 1

In [23]:
x1 = np.concatenate((classes[0],classes[1]))
y1 = np.concatenate((labels[0],labels[1]))
# for i in range(2000):
#     t,b = grad_des(x1,y1,theta1,bias1)
#     theta1 = t
#     bias1 = b
    
print(theta1)


[0.10055399 0.65979212 0.56288563 0.03868751 0.40500411 0.52774836
 0.90952623 0.60902317 0.44042246 0.35228647 0.23809964 0.83175538
 0.76079792 0.65249102 0.77859318 0.82554385 0.08760599 0.44782671
 0.24870423 0.11171974 0.05644657 0.91511332 0.25932164 0.60482642
 0.95980117 0.40337086 0.28001152 0.59582329 0.37892098 0.01045775
 0.3179218  0.91031908 0.84615876 0.43627448 0.50908655 0.06924123
 0.4020001  0.20557833 0.92490045 0.47501873 0.85402762 0.97318038
 0.8044622  0.50431006 0.88048611 0.592924   0.89664275 0.53199249
 0.43074751 0.99068162 0.47061067 0.71709493 0.38684101 0.12337848
 0.69153924 0.01241124 0.93106193 0.9347429  0.99713499 0.78229242
 0.96622409 0.92165525 0.95638822 0.65682596 0.09669044 0.82563354
 0.58058752 0.40651867 0.90564113 0.07752342 0.36606484 0.08563744
 0.86271982 0.68633129 0.13896292 0.31041668 0.94029853 0.26876979
 0.8311865  0.31141499 0.40819874 0.83740935 0.153213   0.30248779
 0.79524362 0.56695285 0.45105948 0.17751885 0.45176863 0.4813

In [25]:
lr = LogisticRegression()
lr.fit(x1,y1)



LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [39]:
xtest = x1[0,:].reshape(1,-1)
lr.predict(xtest)

array([0], dtype=int64)

# for labels 1 and 2

In [41]:
x1 = np.concatenate((classes[1],classes[2]))
y1 = np.concatenate((labels[0],labels[1]))
lr = LogisticRegression()
lr.fit(x1,y1)
lr.predict(xtest)

array([0], dtype=int64)

# for labels 2 and 3

In [43]:
x1 = np.concatenate((classes[2],classes[3]))
y1 = np.concatenate((labels[0],labels[1]))
lr = LogisticRegression()
lr.fit(x1,y1)
lr.predict(xtest)

array([1], dtype=int64)

# for labels 3 and 4

In [44]:
x1 = np.concatenate((classes[3],classes[4]))
y1 = np.concatenate((labels[0],labels[1]))
lr = LogisticRegression()
lr.fit(x1,y1)
lr.predict(xtest)

array([0], dtype=int64)