In [1]:
import numpy as np
import pandas as pd

In [7]:
x = np.array([[1,2,3,0],[4,5,6,1],[7,8,9,1],[4,3,2,0],[1,2,3,0],[4,5,6,1],[7,8,9,1],[4,3,2,0],[1,2,3,0],[4,5,6,1],[7,8,9,1],[4,3,2,0],[1,2,3,0],[4,5,6,1],[7,8,9,1],[4,3,2,0]])
x = sorted(x,key = lambda a:a[3])
for i in x:
    print(i)

[1 2 3 0]
[4 3 2 0]
[1 2 3 0]
[4 3 2 0]
[1 2 3 0]
[4 3 2 0]
[1 2 3 0]
[4 3 2 0]
[4 5 6 1]
[7 8 9 1]
[4 5 6 1]
[7 8 9 1]
[4 5 6 1]
[7 8 9 1]
[4 5 6 1]
[7 8 9 1]


In [13]:
x = np.array(x)
i = x[:,3]
print(i.shape)

(16,)


In [25]:
data = pd.read_csv(r"G:\Coding Blocks\Documents\fashion.csv")
data.head(n=5)

label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0      0       0       0       0       0       0       0       0       9   
1      1       0       0       0       0       0       0       0       0   
2      2       0       0       0       0       0       0      14      53   
3      2       0       0       0       0       0       0       0       0   
4      3       0       0       0       0       0       0       0       0   

   pixel9    ...     pixel775  pixel776  pixel777  pixel778  pixel779  \
0       8    ...          103        87        56         0         0   
1       0    ...           34         0         0         0         0   
2      99    ...            0         0         0         0        63   
3       0    ...          137       126       140         0       133   
4       0    ...            0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  pixel784  
0         0         0         0         0         0  
1         0         0         0         0         0  
2        53        31         0         0         0  
3       224       222        56         0         0  
4         0         0         0         0         0  

[5 rows x 785 columns]

In [27]:
train = data.values
print(type(train))
print(train.shape)
print(train[:5,])

<class 'numpy.ndarray'>
(10000, 785)
[[ 0  0  0 ...  0  0  0]
 [ 1  0  0 ...  0  0  0]
 [ 2  0  0 ...  0  0  0]
 [ 2  0  0 ... 56  0  0]
 [ 3  0  0 ...  0  0  0]]


In [30]:
train = sorted(train,key = lambda x:x[0])
train = np.array(train)
print(train.shape)
print(train[:5,])

(10000, 785)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]]


In [35]:
i = train[:,0]
print(i.shape)
print(i[-1])

(10000,)
9


In [37]:
def idex(i,num):
    return list(i).index(num)

In [43]:
z = idex(i,1)
print(z)

1000


In [64]:
classes = list()
print(i[-1])

9


In [65]:
def construct():
    t = int()
    prev = 0
    for z in range(1,10):
        t = idex(i,z)
        temp = train[prev:t,1:]
        print(temp.shape)
        classes.append(temp)
        prev = t
    temp = train[t:,1:]
    classes.append(temp)

construct()
print(classes[8].shape)

(1000, 784)
(1000, 784)
(1000, 784)
(1000, 784)
(1000, 784)
(1000, 784)
(1000, 784)
(1000, 784)
(1000, 784)
(1000, 784)


In [72]:
print(classes[4])

[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ... 18  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
