### NumPy Practice with Functions on array
- array initialization
- shape function ,, Shape is an attribute not function
- Two Dimensional array
- Create zeros , ones and custom array
- Array of some constant , Full function
- Identity matrix with eye function
- Random Matrix with NumPy.random.random
- Array indexing
- Mathematical operations
- array.sum() function with axis wise addition
- stacking of arrays using stack function with axis wise stacking
- reshape an array

In [3]:
import numpy as np

x = np.array([1,2,3,4,5])
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
print(x.shape)

(5,)


In [5]:
y = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(y)
print(y.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


###### Creating custom arrays

In [11]:
import numpy as np
ze = np.zeros([2,3])
print(ze)

[[0. 0. 0.]
 [0. 0. 0.]]


#### Array full of one number

In [12]:
n = np.full([3,3],1)
print(n)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


#### Indentity Matrix

In [17]:
i = np.eye(3)
print(i)

z = np.array([[1,2,3],[12,2,1],[3,0,1]])
print(z.dot(i))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 1.  2.  3.]
 [12.  2.  1.]
 [ 3.  0.  1.]]


## Random Matrix ***

In [6]:
ran = np.random.random([2,2])
print(ran)

[[0.72679511 0.06054852]
 [0.92117156 0.02527883]]


### Indexing and slicing

In [21]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
 
# Slicing array
temp = arr[:2, ::2]
print ("Array with first 2 rows and alternate"
                    "columns(0 and 2):\n", temp)
 
# Integer array indexing example
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]
print ("\nElements at indices (0, 3), (1, 2), (2, 1),"
                                    "(3, 0):\n", temp)
 
# boolean array indexing example
cond = arr > 0 # cond is a boolean array
temp = arr[cond]
print ("\nElements greater than 0:\n", temp)

Array with first 2 rows and alternatecolumns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]

Elements at indices (0, 3), (1, 2), (2, 1),(3, 0):
 [4. 6. 0. 3.]

Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


## Sum method with Axis

In [28]:
s = np.array([[1,2,3],[3,4,5]])
print(s.sum(axis=1))
### Other way of writing it
print(np.sum(s,axis=0))

[ 6 12]
[4 6 8]


# Reshaping an array

In [37]:
print(s.reshape(1,-1),end = "\n")
print()
print(s.reshape(3,-1))
print()
print(s.reshape(3,2,-1))

[[1 2 3 3 4 5]]

[[1 2]
 [3 3]
 [4 5]]

[[[1]
  [2]]

 [[3]
  [3]]

 [[4]
  [5]]]


# Stacking an array = Interesting

In [43]:
n1 = np.array([1,2,3])
n2 = np.array([3,4,5])

print(np.stack([n1,n2],axis = 1))


[[1 3]
 [2 4]
 [3 5]]
